### ISSUE TITLE
I am getting "java.util.ServiceConfigurationError: de.retest.recheck.RecheckAdapter: Provider de.retest.web.RecheckSeleniumAdapter could not be instantiated",

### ISSUE THREAD

**Issue by YusufK007** [retest/recheck#661] opened 2020-02-21 13:50 UTC
*Before submission, please check that ...*

- [x] this is related specifically to recheck and not its extension (e.g. [recheck-web](https://github.com/retest/recheck-web)).
- [x] the [documentation](https://docs.retest.de/) does not mention a fix (e.g. wrong API usage, ...).
- [x] the bug is not related to a customization (e.g. custom implementations).
- [x] there are no open or closed issues that are related to this problem.

### How to Reproduce?

1. ... 
2. ...
3. ...

### Setup

- recheck: [e.g. 1.6.0]
- Testing framework: [e.g. JUnit5 5.5.2, TestNG 7.0.0]
- OS: [e.g. MacOS 14, Windows 10]
- Java version: [e.g. OpenJDK 11]

**Comment by YusufK007** [comment] 2020-02-21 13:55
I am using Maven project of Selenium,Junit with Cucumber .I have a question that do recheck web support cucumber ? if yes can you tell me how to implement it in cucumber ? 
Below is snippet of my error , 
![image](https://user-images.githubusercontent.com/61319947/75039997-d6d7b380-5487-11ea-999a-b91f8a67b3d7.png)

**Comment by YusufK007** [comment] 2020-02-21 14:00
My Setup 
recheck: [1.9.0]
Testing framework: [Selenium 3.141.59, JUnit5 5.5.2, Cucumber 1.2.0]
OS: [ Windows 10]
Java version: [JDK 1.8.0_171]

**Comment by beatngu13** [comment] 2020-02-21 14:41
Hi @YusufK007,

based on the screenshot you have posted, it looks like recheck cannot identify the test class (see inner `IllegalStateException`). This is likely because you have a (to us) non-default test setup. We assume the following setup:

https://docs.retest.de/recheck/introduction/usage/#using-plain-junit-5

Could you please paste the code of your JUnit test?

If you have to use a different setup due to Cucumber, check out the following link (especially `NamingStrategy`):

https://docs.retest.de/recheck/introduction/usage/#lifecycle

And this issue from recheck-web:

https://github.com/retest/recheck-web/issues/429

**Comment by YusufK007** [comment] 2020-02-24 14:44
i used the naming strategy and I am using cucumber junit to test. Below is the code i have used 

```java
@Before
public static void setupTest( Scenario scenario ) throws Exception {

	ScenarioName = scenario.getName();
	System.setProperty( "webdriver.chrome.driver", System.getProperty( "user.dir" ) + "/exe/chromedriver.exe" );

	ChromeOptions options = new ChromeOptions();
	options.addArguments( "--allow-running-insecure-content" );
	options.addArguments( "--allow-insecure-websocket-from-https-origin" );
	options.addArguments( "disable-extensions" );
	options.setExperimentalOption( "useAutomationExtension", false );
	driver = new UnbreakableDriver( new ChromeDriver( options ) );
	ops = RecheckOptions.builder().namingStrategy( new ClassAndMethodBasedShortNamingStrategy() )
			.projectLayout( new GradleProjectLayout() ).suiteName( "testName2" ).ignoreNothing().build();

	re = new RecheckWebImpl( ops );
	re.startTest( "Test" );
}

@Given( "^Test$" )
public void Test() throws Throwable {
	try {
		driver.get( url );

		Thread.sleep( 10000 );
		re.check( driver, "ini" );
		user.takeScreenshot( driver );
	} catch ( Exception e ) {
		e.printStackTrace();
		user.takeScreenshot( driver );
		throw e;
	}
}

@After
public static void tearDown( Scenario result ) throws Exception {
	re.cap();
}
```

I am getting the same error that  "Couldn't identify test class in call stack".

**Comment by beatngu13** [comment] 2020-02-24 15:59
Hi @YusufK007,

I haven't worked with Cucumber before, but I just did a quick smoke test based on your snippet:

```java
private static UnbreakableDriver driver;
private static RecheckWebImpl re;

@Before
public static void setupTest( final Scenario scenario ) throws Exception {
	driver = new UnbreakableDriver( new ChromeDriver() );
	re = new RecheckWebImpl( RecheckOptions.builder() //
			.projectLayout( new GradleProjectLayout() ) //
			.suiteName( scenario.getName() ) //
			.build() );
}

@Given( "^Test$" )
public void searchGoogleTest() throws Throwable {
	re.startTest("search-google");
	driver.get( "https://google.de/" );
	Thread.sleep( 500 );
	re.check( driver, "ini" );
}

@After
public static void tearDown( final Scenario result ) throws Exception {
	re.cap();
	driver.quit();
}
```

This seems to work, at least I don't get the exception you are mentioning.

Have you had a look at the [Cucumber with recheck-web example project](https://github.com/diba1013/recheck-web-cucumber-demo)?

**Comment by YusufK007** [comment] 2020-02-25 14:18
I did have a look at the Cucumber project and i have implemented in pretty much the same way in my project as well . I tried running my project with Junit and its working , the golden master is getting created but It is giving the above error when i run with maven or cucumber feature directly .
I have one more query that any change in html element's id is not reflected in the reports , like if id gets removed or changed it is not showing in the reports .

**Comment by diba1013** [comment] 2020-02-25 17:43
I updated my demo project to the newest cucumber 5.4.0 and recheck-web 1.9.0 versions. I also integrated CI to make sure that the tests are executed via maven.

Since I started the tests always from the IDE, I looked into executing cucumber with maven. I did not look into directly starting the test with cucumber.

According to the [cucumber docs](https://cucumber.io/docs/tools/java/#maven), you need to pass some options as arguments so that cucumber can identify the tests to be executed. However, for my project it worked out of the box, probably because I define them via the [annotation](https://github.com/diba1013/recheck-web-cucumber-demo/blob/master/src/test/java/de/diba/recheck/web/cucumber/RunCucumberTest.java#L9).

Did you make sure that the scenario is executed when running in maven? Usually the creation of a Golden Master is a great indicator that the test is working and thus correctly executed. However I am unsure why the same test cannot be executed by maven. Did you try to [execute a single test](https://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html) via surefire?

As stated, we have no real experience with cucumber, therefore we can only provide basic trouble shooting:

1. Make sure that the test is executed properly. Maybe debug to verify.
2. Make sure that the suite name and the test name is set manually before any `Recheck#check()` gets executed. From the provided example as well as our adapted example, this is the case. You can choose either option:

    1. Set the suite name set via `RecheckOptionsBuilder.suiteName(String)` and `Recheck#startTest(String)`. Do not use the empty parameter methods, as it will trigger the automatic detection, which seem to fail for you in certain cases. 
    2. Alternatively you can provide a [`NamingStrategy`](https://github.com/retest/recheck/blob/master/src/main/java/de/retest/recheck/persistence/NamingStrategy.java) (or [docs](https://docs.retest.de/recheck/introduction/usage/#modifying-the-lifecycle)) where you return these names. Refrain from using any provided `NamingStrategy` that uses `TestCaseFinder.getInstance()` as this is our automatic detecting feature which currently works only for JUnit4/5 and TestNG annotations. 

Lastly I can only ask to send a minified project (please use either email or provide a public repository) as our attempts to reproduce this issue failed in that terms that it works for us.

Thanks for your patience!

**Comment by YusufK007** [comment] 2020-02-26 14:24
Actually it does not matter if I run it with Junit or Maven ,So its not the problem for me now as it is working and golden master is getting created . In meanwhile i will try to debug my code to check why it is not working with maven and also after creating golden master i have encountered few more problems so it will be very helpful of you guys to help me out on this  .
1) Firstly as I said above that any change in html element's "id" is not reflected in the reports , like if "id" gets removed or changed it is not showing in the reports . so is it expected ? As I would like to to get change in "id" also reported because "id" of the elements get changed most often in my project.
2) Secondly when i am trying to pass any Web element directly in Recheck#check() method i am getting an error as "Must first call a check-method with an UnbreakableDriver before being able to load a Golden Master (needed for unbreakable tests)!" 
below is the screenshot of my error, all i did was just passing web element directly in check method instead of the driver like re.check(driver.findElementById("fn1"),"FirstName");
![image](https://user-images.githubusercontent.com/61319947/75353586-acb43600-5879-11ea-9bd0-eb7e7429bff0.png)

**Comment by diba1013** [comment] 2020-02-26 14:40
> So its not the problem for me now as it is working and golden master is getting created

Ok, that is great.

> It will be very helpful of you guys to help me out on this

I will try to reproduce and provide fixes if this does not work.

**Comment by diba1013** [comment] 2020-02-26 17:30
I trew togther a basic JUnit5 Test:

```html
<!DOCTYPE html>
<html id="root" lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
</body>
</html>
```

```java
@ExtendWith( RecheckExtension.class )
class UnbreakableDriverIT {

	Recheck re;
	WebDriver driver;

	@BeforeEach
	void setUp() {
		re = new RecheckWebImpl();
		driver = new UnbreakableDriver( WebDriverFactory.driver( WebDriverFactory.Driver.CHROME ) );
	}

	@AfterEach
	void tearDown() {
		driver.quit();
	}

	@Test
	void change_for_the_id_of_html_should_get_notified() {
		driver.get( getClass().getResource( "UnbreakableDriverIT.html" ).toExternalForm() );

		re.check( driver, "initial" );
	}
}
```
After executing it twice to ensure a passing build, I did the following change to the site:

```diff
<!DOCTYPE html>
-<html id="root" lang="en">
+<html id="html" lang="en">
<head>
```

and executed again to get the following change:

```
1 check(s) in 'de.retest.web.selenium.UnbreakableDriverIT' found the following difference(s):
Test 'change_for_the_id_of_html_should_get_notified' has 1 difference(s) in 1 state(s):
element resulted in:
	html at 'html[1]':
		id: expected="root", actual="html"
```
Removing the id also works for me.

Notice that I changed the id after the Golden Master creation. Currently we do not see a use case to detect changes during the runtime of a test. That means, our use case is as follows:

1. Create your Golden Master with the current state.
2. Do changes to your web application.
3. Execute the test again to see the changes.

If you need to have runtime changes, you are free to [reuse Golden Masters](https://docs.retest.de/recheck/introduction/usage/#reuse-golden-master-files). Notice the same name for the checks:

```java 
@Test
void change_for_the_id_of_html_should_get_notified() {
    driver.get( getClass().getResource( "UnbreakableDriverIT.html" ).toExternalForm() );

    re.check( driver, "name" );

    // perform some action that changes the id (e.g. execute javascript or click a button)
    ((JavascriptExecutor) driver).executeScript( "document.getElementById('root').id='html'" );

    re.check( driver, "name" );
}
```
Executing this test twice results in the same result.

Some potential troubleshooting:

1. Did you [ignore](https://docs.retest.de/recheck/usage/filter/) any elements or attributes? You are most likely looking for something like `attribute=id` to have it filtered from the reported result. To check this, you could simply remove the `${project_root}/.retest` folder to have it regenerated with the next run.

---

Regarding your other issue: I could reproduce it and created a fix for that which will be part of the next release: retest/recheck-web#530

**Comment by YusufK007** [comment] 2020-02-28 13:22
Thank you after resetting ${project_root}/.retest i was able to get "id" in my reports. I have two more questions though,
1) Do Recheck-web support Robot Framework? Do you have any python libraries?
2) My project uses dynamic web elements , I get a lot of differences in my report like "div was inserted" ,"span was deleted" and so on . i can ignore all the div and span in recheck.ignore file but then it will not show me any genuine change in these elements . So is there any other way to deal with dynamic web pages ?

**Comment by diba1013** [comment] 2020-02-28 13:45
> `${project_root}/.retest` i was able to get "id" in my reports

Great. That is still a issue that we need to address, since it is not transparent what attributes and such is ignored and thus it can quite easily happen that attributes are ignored that you want to keep (in your case the `id`).

> Do Recheck-web support Robot Framework

I am not familiar with that library. I assume you refer to https://github.com/robotframework/robotframework.

recheck-web builds on top of Selenium which is a browser automation software. Therefore recheck-web is independent of any frameworks, as long as you can get a `WebDriver` or `WebElement` from the framework.

If you do not want to write tests, we are developing an [AI](https://retest.de/ai-based-test-generation/), which will create and execute tests for you.

> Do you have any python libraries

Currently, we are focusing on selenium-java, thus we currently provide an API in Java. However, we plan to support additional programming languages in the future.

> My project uses dynamic web elements

As a matter of fact, we addressed issues with the filter syntax in the current development cycle and are working on a release right now. You will be able to ignore insertions or deletions via (`matcher: type=div, change=inserted` or `matcher: type=span, change=deleted`) to ignore deletions for any span or children thereof, while still being able to see differences to the element itself if they occur. I will inform you once we have a beta release available, so that you can test it if you wish.

We are working quite heavily on improving the filter syntax, as dynamic/compley changes are only able to be ignored via the [JavaScript `recheck.ignore.js`](https://docs.retest.de/recheck/usage/filter/#recheckignorejs). We are happy to hear feedback and suggestions on what can be improved for actual use cases so that we can add features to the syntax.

**Comment by diba1013** [comment] 2020-03-05 12:10
A new release for recheck-web is available. You can find the release [here]( https://github.com/retest/recheck-web/releases), via [jitpack](https://jitpack.io/#retest/recheck-web), or on [maven-central](https://mvnrepository.com/artifact/de.retest/recheck-web).

**Comment by diba1013** [comment] 2020-03-05 12:11
Since this seems to be fixed, I will close this now. If you or any other still have problems, please comment and reopen this issue. If you found another problem, please report this as a new issue.

**Closed as completed by diba1013** 2020-03-05 12:11 UTC
Labels: bug

**Comment by YusufK007** [comment] 2020-03-11 11:53
Hey I used your latest release v1.10.1 and I got one new issue. I tried implementing re.check(driver.findElementById("fn1"),"FirstName"), by passing a web element in check method and it worked. All separate golden master got created for specific web elements but when the xpath of any web element changes the test breaks with "org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element:" . like i was using id to identify an input called "First Name" but when id of "First Name" changed, i got above mentioned above error . Below is the snippet of my code

**Comment by YusufK007** [comment] 2020-03-11 11:57
class MySeleniumTest {

	UnbreakableDriver driver;
	Recheck re;
	@BeforeEach
	void setup() {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\testpf11251\\Documents\\recheck-web-example-master\\driver\\chromedriver.exe");
		// Use the RecheckDriver as a wrapper for your usual driver.
		ChromeOptions options = new ChromeOptions();
		options.addArguments("--allow-running-insecure-content");
		options.addArguments("--allow-insecure-websocket-from-https-origin");
		options.addArguments("disable-extensions");
		options.setExperimentalOption("useAutomationExtension", false);//(arguments)
		
		driver = new UnbreakableDriver( new ChromeDriver(options) );
		// Use the unbreakable recheck implementation.
		re = new RecheckWebImpl();
		//driver = new RecheckDriver( new ChromeDriver() );
		//re = new RecheckImpl();
	}
	@Test
	public void test() throws Exception {
		try
		{
		re.startTest("test-name60");
		String url = Paths.get( "src/test/resources/demo-app_btn-change.html" ).toUri().toURL().toString();
		driver.get(url);
		
		
		driver.findElement(By.id("fn1")).sendKeys("Yusuf");
		re.check(driver.findElementById("fn1"),"FirstName");
		driver.findElement(By.id("ln1")).sendKeys("Kundawala");
		re.check(driver.findElementById("ln1"),"LastName");
		driver.findElement(By.id("username")).sendKeys("Yusuf");
		re.check(driver.findElementById("username"),"Username");
		driver.findElement(By.id("password")).sendKeys("secret");
		re.check(driver.findElementById("password"),"Password");
	
		re.check(driver.findElementById("sign-in"),"Sign-in");
		driver.findElement(By.id("sign-in")).click();
		
		
		
		assertEquals(driver.findElement(By.tagName("h4")).getText(), "Success!");
		re.capTest();
		//throw new PendingException();
		}
		catch(Exception e)
		{
			e.printStackTrace();
			throw e;
		}
	}

	@AfterEach
	void tearDown() throws InterruptedException {
		driver.quit();
		re.cap();
	}

**Comment by diba1013** [comment] 2020-03-11 14:22
Using the Golden Masters with the `UnbreakableDriver` is like a checkpoint. Each action (`findElementById`) until the next checkpoint utilizes the previous Golden Master to find elements in.

With your test setup, the first two actions do not have a Golden Master to reference, thus it fails, because it cannot look into the previous Golden Master as it is non existent. 

To solve this (I have adjusted that in the [documentation](https://docs.retest.de/recheck-web/introduction/usage/#unbreakable-tests) already), is to create a initial check with the driver right after `driver.get(url)`.

```java
String url = Paths.get( "src/test/resources/demo-app_btn-change.html" ).toUri().toURL().toString();
driver.get(url);

re.check(driver, "initial");

driver.findElement(By.id("fn1")).sendKeys("Yusuf");
...
```

That way, the "initial" Golden Master is the checkpoint to reference, containing the complete state if any information goes missing (e.g. `id`).

With my tests, using such an initial check resolves the issue that you are having.

**Comment by YusufK007** [comment] 2020-03-12 08:21
I did "initial" Golden Master as you suggested but still the test breaks if "Id" of any elements changes and goes missing . Note when I only did the "initial" check like re.check(driver,"initial")  without the specific elements check like re.check(driver.findElementById("fn1"),"FirstName") it worked , The test did not break but when i used the same setup with re.check(driver,"initial") after driver.get(url) followed by the specific elements check before any actions performed with that elements like i have used in my code above , the test breaks that time with the error same as above in line ,"re,check(driver.findElementById("fn1"),"FirstName")" . 
I am using specific explicit elements check as my project uses dynamic web pages and there are too many differences reported if i use implicit checking or explicit driver check.

**Comment by diba1013** [comment] 2020-03-12 09:02
Ok, let's see if I understood you correctly:

For clarity, I separated the `driver.findElementById` from the actions and checks. That is because the `driver.findElementById` does the unbreakable work as to look into the last Golden Master and try to find the changed element, if it cannot be found in the current website.

When you do the initial driver check, but get rid of the element checks, the test works

```java
String url = Paths.get( "src/test/resources/demo-app_btn-change.html" ).toUri().toURL().toString();
driver.get(url);
re.check(driver, "initial");

var fn1 = driver.findElement(By.id("fn1")); // reference "initial" check
fn1.sendKeys("Yusuf"); 

var ln1 = driver.findElement(By.id("ln1")); // reference "initial" check
ln1.sendKeys("Kundawala");

var username = driver.findElement(By.id("username"));  // reference "initial" check
username.sendKeys("Yusuf");

var password = driver.findElement(By.id("password")); // reference "initial" check
password.sendKeys("secret");

var sign = driver.findElementById("sign-in"); // reference "initial" check
re.check(sign, "Sign-in");

assertEquals(driver.findElement(By.tagName("h4")).getText(), "Success!");
```

But as soon as you insert the element checks, the test breaks:

```java
String url = Paths.get( "src/test/resources/demo-app_btn-change.html" ).toUri().toURL().toString();
driver.get(url);
re.check(driver, "initial");

var fn1 = driver.findElement(By.id("fn1")); // reference "initial" check
fn1.sendKeys("Yusuf");
re.check(fn1, "FirstName"); // create new reference "FirstName"

var ln1 = driver.findElement(By.id("ln1")); // reference "FirstName" check
ln1.sendKeys("Kundawala");
re.check(driver.findElementById("ln1"),"LastName"); // create new reference "LastName"

var username = driver.findElement(By.id("username"));  // reference "LastName" check
username.sendKeys("Yusuf");
re.check(username, "Username"); // create new reference "Username"

var password = driver.findElement(By.id("password")); // reference "Username" check
password.sendKeys("secret");
re.check(password, "Password"); // create new reference "Password"

var sign = driver.findElementById("sign-in"); // reference "Password" check
re.check(sign, "Sign-in"); // create new reference "Sign-in"
driver.findElement(sign).click();

assertEquals(driver.findElement(By.tagName("h4")).getText(), "Success!");
```

Note a `re.check` will create a new reference point, that means the `driver.findElementById` does always reference to the **last** check. If this check was performed with an element, it does only include the scope of the element. That means the element itself and its children. If this the element to search for is not included in that scope, the element can never be found, thus the exception you are getting.

## Suggestion

As long as you do not navigate to a new state of your web application, you could do the `driver.findElementById` after the initial check. That way, the only reference available is the whole web application and therefore all buttons can be found. Note that this might not work for dynamic websites (e.g. the id is only set after the username has been set).

```java
String url = Paths.get( "src/test/resources/demo-app_btn-change.html" ).toUri().toURL().toString();
driver.get(url);
re.check(driver, "initial");

var fn1 = driver.findElement(By.id("fn1")); // reference "initial" check
var ln1 = driver.findElement(By.id("ln1")); // reference "initial" check
var username = driver.findElement(By.id("username"));  // reference "initial" check
var password = driver.findElement(By.id("password")); // reference "initial" check
var sign = driver.findElementById("sign-in"); // reference "initial" check

fn1.sendKeys("Yusuf");
re.check(fn1, "FirstName"); // create new reference "FirstName"

ln1.sendKeys("Kundawala");
re.check(driver.findElementById("ln1"),"LastName"); // create new reference "LastName"

username.sendKeys("Yusuf");
re.check(username, "Username"); // create new reference "Username"

password.sendKeys("secret");
re.check(password, "Password"); // create new reference "Password"

re.check(sign, "Sign-in"); // create new reference "Sign-in"
driver.findElement(sign).click();

assertEquals(driver.findElement(By.tagName("h4")).getText(), "Success!");
```

This would be somewhat in line with the [Page Object Pattern](https://webdriver.io/docs/pageobjects.html) as you create a Page Object in the beginning and reuse the extracted elements annotated by `@FindBy`.

---

I will try to clarify this behavior in the [documentation](https://docs.retest.de/recheck-web/introduction/usage/#unbreakable-tests). Secondly, I will talk to the team if we think it would be feasible to implement something like a `UnbreakableStrategy` which tells the `UnbreakableDriver` to reference only the last driver check and ignore element checks. I want to emphasize that it is not be feasible (performance-wise and logic-wise) to look at each Golden Master created to try to find the element in question.
