### ISSUE TITLE
Integration with SoapUI

### ISSUE THREAD

**Issue by lhimo** [retest/recheck#301] opened 2019-06-29 12:38 UTC
Hi,

I'm trying to use recheck within a groovy script in SoapUI, in order to integrate it in my selenium suite. I get the following error:

```
ERROR:java.lang.IllegalStateException: Couldn't identify test class in call stack. 
This is needed to dynamically name the Golden Master files. 
 Please instantiate RecheckImpl with RecheckOptions, and provide a different FileNamerStrategy.
```

by calling either `new RecheckImpl()` as well as `RecheckWebImpl()`. Can I pass a parameter of some sort?

Thanks

**Comment by beatngu13** [comment] 2019-07-03 11:18
Hey @lhimo,

You usually get this exception when you don't run your tests with JUnit Vintage (v4), JUnit Jupiter (v5) or TestNG. We derive the Golden Master file names from the test class/method names by searching for particular annotations (such as JUnit's `@Test`) in the call stack. And we have several implementations that determine the path of those Golden Masters (e.g. [`MavenConformFileNamerStrategy`](https://github.com/retest/recheck/blob/master/src/main/java/de/retest/recheck/MavenConformFileNamerStrategy.java)). (Check out the corresponding docs [here](https://retest.github.io/docs/recheck/location-of-the-golden-master-files-and-test-reports/).)

However, you can provide a custom [`FileNamerStrategy`](https://github.com/retest/recheck/blob/master/src/main/java/de/retest/recheck/FileNamerStrategy.java). You can then pass it to `RecheckImpl` or `RecheckWebImpl` via `RecheckOptions`:

```java
RecheckOptions options = RecheckOptions.builder()
		.fileNamerStrategy( myCustomeFileNamerStrategy )
		.build();
Recheck re = new RecheckImpl( options );
```

Does this solve your problem?

**Comment by lhimo** [comment] 2019-07-05 15:45
Thanks, I tried but I get the same error... How exactly can I define a custom FileNamerStrategy? My attempt:

```
public class SoapUIConformFileNamerStrategy implements FileNamerStrategy{

public static final String DEFAULT_RETEST_PROJECT_PATH = new File('').absolutePath;
public static final String DEFAULT_RETEST_TESTREPORTS_PATH = new File('TestReports').absolutePath;

FileNamer createFileNamer( String... baseNames ){
		return new FileNamer() {
			@Override
			public File getFile( final String extension ) {
				return toFile( DEFAULT_RETEST_PROJECT_PATH, extension, baseNames );
			}

			@Override
			public File getResultFile( final String extension ) {
				return toFile( DEFAULT_RETEST_TESTREPORTS_PATH, extension, baseNames );
			}
		}
};

String getTestClassName() {
		return testRunner.testCase.name
	};
	
String getTestMethodName() {
		return testRunner.testCase.testSuite.name
	};
}
```

**Comment by beatngu13** [comment] 2019-07-08 15:08
Your `SoapUIConformFileNamerStrategy` looks fine at first glance, although it doesn't seem to compile. For instance, you probably mean `new File("TestReports").getAbsolutePath()`, using `"` instead of `'` and `.getAbsolutePath()` instead of `.absolutePath`. I also don't know what the result of `testRunner.testCase.name` is, respectively, where the variable comes from (it is not a field of the class).

However, could you show me a) your test, b) your (compilable) `SoapUIConformFileNamerStrategy`, and c) the _exact_ error message you get (including the stack trace)? Thanks.

**Comment by lhimo** [comment] 2019-07-09 07:54
I tried to compile it inside the 'Groovy script' test step of SoapUI. If I print the absolute paths I get the correct results, I guess SoapUI has a slightly different syntax for some reason. Also the commands `testRunner.testCase.name` and `testRunner.testCase.testSuite.name` seem to return the correct strings.

I'm attaching the script [groovy-script-recheck.txt](https://github.com/retest/recheck/files/3371806/groovy-script-recheck.txt). The jars files I included in the SoapUI folder are: recheck-1.2.0.jar, recheck-web-1.1.0.jar, selenium-api-3.141.59.jar and selenium-java-3.141.59.jar. The error I get is:

```
Tue Jul 09 09:31:32 CEST 2019:ERROR:java.lang.IllegalStateException: Couldn't identify test class in call stack. 
This is needed to dynamically name the Golden Master files. 
 Please instantiate RecheckImpl with RecheckOptions, and provide a different FileNamerStrategy.
   java.lang.IllegalStateException: Couldn't identify test class in call stack. 
   This is needed to dynamically name the Golden Master files. 
    Please instantiate RecheckImpl with RecheckOptions, and provide a different FileNamerStrategy.
   	at de.retest.recheck.FileNamerStrategy.lambda$getTestClassName$0(FileNamerStrategy.java:29)
   	at java.util.Optional.orElseThrow(Unknown Source)
   	at de.retest.recheck.FileNamerStrategy.getTestClassName(FileNamerStrategy.java:29)
   	at de.retest.recheck.RecheckOptions.$default$suiteName(RecheckOptions.java:7)
   	at de.retest.recheck.RecheckOptions.<init>(RecheckOptions.java:7)
   	at de.retest.recheck.RecheckOptions$RecheckOptionsBuilderImpl.build(RecheckOptions.java:7)
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   	at java.lang.reflect.Method.invoke(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:233)
   	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
   	at de.retest.web.it.Script16.run(Script16.groovy:61)
   	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:90)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
   	at com.eviware.soapui.impl.wsdl.panels.teststeps.GroovyScriptStepDesktopPanel$RunAction$1.run(GroovyScriptStepDesktopPanel.java:250)
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   	at java.lang.Thread.run(Unknown Source)

```

**Comment by beatngu13** [comment] 2019-07-09 08:09
Ah, it's Groovy! Sorry, my bad … thought it's Java.

The problem is:

```java
RecheckOptions options = RecheckOptions.builder()
        .fileNamerStrategy( new SoapUIConformFileNamerStrategy() )
        .build();
```

Here you also have to set the suite name:

```java
FileNamerStrategy fileNamerStrategy = new SoapUIConformFileNamerStrategy();
RecheckOptions options = RecheckOptions.builder()
        .fileNamerStrategy( fileNamerStrategy )
        .suiteName( fileNamerStrategy.getTestClassName() )
        .build();
```

It's essentially a problem in our builder, which doesn't reuse the given `FileNamerStrategy`. We will fix that.

However, does it work for you now?

**Comment by lhimo** [comment] 2019-07-09 09:08
Now it's going through, but adding the line `re = new RecheckWebImpl( options );` I get:

```
Tue Jul 09 11:05:32 CEST 2019:ERROR:java.lang.RuntimeException: Project root could not be found.
   java.lang.RuntimeException: Project root could not be found.
   	at de.retest.recheck.configuration.ProjectConfiguration.lambda$findProjectConfigFolder$1(ProjectConfiguration.java:48)
   	at java.util.Optional.orElseThrow(Unknown Source)
   	at de.retest.recheck.configuration.ProjectConfiguration.findProjectConfigFolder(ProjectConfiguration.java:48)
   	at de.retest.recheck.configuration.ProjectConfiguration.ensureProjectConfigurationInitialized(ProjectConfiguration.java:52)
   	at de.retest.recheck.RecheckImpl.<init>(RecheckImpl.java:77)
   	at de.retest.web.RecheckWebImpl.<init>(RecheckWebImpl.java:20)
   	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
   	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
   	at java.lang.reflect.Constructor.newInstance(Unknown Source)
   	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
   	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
   	at de.retest.web.it.Script25.run(Script25.groovy:84)
   	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:90)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
   	at com.eviware.soapui.impl.wsdl.panels.teststeps.GroovyScriptStepDesktopPanel$RunAction$1.run(GroovyScriptStepDesktopPanel.java:250)
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   	at java.lang.Thread.run(Unknown Source)

```

**Comment by beatngu13** [comment] 2019-07-09 10:01
Based on the current working directory, we look for the project root (containing e.g. the `.retest` folder) by searching in all parent folders. If you use a non-standard Maven project layout, then you can use the system property `ProjectConfiguration#RETEST_PROJECT_ROOT`, i.e., `de.retest.recheck.project.root` to point to the project root. For instance:

```java
System.setProperty( ProjectConfiguration.RETEST_PROJECT_ROOT, "/path/to/project/root/" );
```

Please ensure that there is a `.retest` folder, even if it's empty.

(Sorry for the inconvenience, will adapt the docs accordingly.)

**Comment by lhimo** [comment] 2019-07-09 10:17
Unfortunately I'm getting the following:

```
Tue Jul 09 12:14:14 CEST 2019:ERROR:groovy.lang.MissingPropertyException: No such property: ProjectConfiguration for class: de.retest.web.it.Script33
   groovy.lang.MissingPropertyException: No such property: ProjectConfiguration for class: de.retest.web.it.Script33
   	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
   	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
   	at de.retest.web.it.Script33.run(Script33.groovy:73)
   	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:90)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
   	at com.eviware.soapui.impl.wsdl.panels.teststeps.GroovyScriptStepDesktopPanel$RunAction$1.run(GroovyScriptStepDesktopPanel.java:250)
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   	at java.lang.Thread.run(Unknown Source)

```

**Comment by beatngu13** [comment] 2019-07-09 11:23
This appears to be a Groovy-specific exception—and I'm not that familiar with Groovy. Could you show your current script? How do you set the property there? AFAIK system properties can be set like:

```groovy
System.properties['apple.laf.useScreenMenuBar'] = '/path/to/project/root/'
```

**Comment by lhimo** [comment] 2019-07-09 15:24
Ok, the correct syntax seems to be `System.setProperty( "de.retest.recheck.project.root", dataFolder );`. However, now I'm getting:

```
Tue Jul 09 17:19:18 CEST 2019:ERROR:groovy.lang.MissingMethodException: No signature of method: de.retest.web.it.SoapUIConformFileNamerStrategy.toFile() is applicable for argument types: (java.lang.String, java.lang.String, [Ljava.lang.String;) values: [ "path to my project", , [test case name]]
Possible solutions: notify(), find()
```

**Comment by beatngu13** [comment] 2019-07-09 16:00
You seem to invoke `SoapUIConformFileNamerStrategy.toFile()` with wrong arguments. Could you show me your current implementation of `SoapUIConformFileNamerStrategy`? And, if possible, the stack trace of the error?

**Comment by lhimo** [comment] 2019-07-09 16:08
Sure, here is the current script:

```
public class SoapUIConformFileNamerStrategy implements FileNamerStrategy{

protected testRunner
protected context
protected log 
protected dataFolder

public static final String DEFAULT_RETEST_PROJECT_PATH = "C:/Users/gitlab/project";
public static final String DEFAULT_RETEST_TESTREPORTS_PATH = "C:/Users/gitlab/project/TestReports";

FileNamer createFileNamer( String... baseNames ){
		return new FileNamer() {
			@Override
			public File getFile( final String extension ) {
				return toFile( DEFAULT_RETEST_PROJECT_PATH, extension, baseNames );
			}

			@Override
			public File getResultFile( final String extension ) {
				return toFile( DEFAULT_RETEST_TESTREPORTS_PATH, extension, baseNames );
			}
		}
};

String getTestClassName() {
		return testRunner.testCase.name
	}
	
String getTestMethodName() {
		return testRunner.testCase.testSuite.name
	}
}
```
and the stacktrace:

```
Tue Jul 09 18:05:19 CEST 2019:ERROR:groovy.lang.MissingMethodException: No signature of method: de.retest.web.it.SoapUIConformFileNamerStrategy.toFile() is applicable for argument types: (java.lang.String, java.lang.String, [Ljava.lang.String;) values: [ "C:/Users/gitlab/project", , [test case name] ]
Possible solutions: notify(), find()
   groovy.lang.MissingMethodException: No signature of method: de.retest.web.it.SoapUIConformFileNamerStrategy.toFile() is applicable for argument types: (java.lang.String, java.lang.String, [Ljava.lang.String;) values: [ "C:/Users/gitlab/project", , [test case name] ]
   Possible solutions: notify(), find()
   	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
   	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:95)
   	at de.retest.web.it.SoapUIConformFileNamerStrategy.this$dist$invoke$1(Script81.groovy)
   	at de.retest.web.it.SoapUIConformFileNamerStrategy$1.methodMissing(Script81.groovy)
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   	at java.lang.reflect.Method.invoke(Unknown Source)
   	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
   	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:936)
   	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1259)
   	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
   	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
   	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
   	at de.retest.web.it.SoapUIConformFileNamerStrategy$1.getFile(Script81.groovy:43)
   	at de.retest.recheck.RecheckImpl.getSuitePath(RecheckImpl.java:153)
   	at de.retest.recheck.RecheckImpl.<init>(RecheckImpl.java:85)
   	at de.retest.web.RecheckWebImpl.<init>(RecheckWebImpl.java:20)
   	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
   	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
   	at java.lang.reflect.Constructor.newInstance(Unknown Source)
   	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
   	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
   	at de.retest.web.it.Script81.run(Script81.groovy:98)
   	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:90)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
   	at com.eviware.soapui.impl.wsdl.panels.teststeps.GroovyScriptStepDesktopPanel$RunAction$1.run(GroovyScriptStepDesktopPanel.java:250)
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   	at java.lang.Thread.run(Unknown Source)

```

**Comment by beatngu13** [comment] 2019-07-09 16:14
I can't find a definition of the `toFile` method that you are using in `SoapUIConformFileNamerStrategy`, which is probably the reason for the `MissingMethodException`. Here is the implementation from `MavenConformFileNamerStrategy`, add it to your `FileNamerStrategy`:

```java
private File toFile( final String prefix, final String extension, final String... baseNames ) {
	final String baseName = String.join( File.separator, baseNames );
	return new File( prefix + File.separator + Properties.RECHECK_FOLDER_NAME + File.separator + baseName + extension );
}
```

Where `Properties` is `de.retest.recheck.Properties`.

**Comment by lhimo** [comment] 2019-07-09 16:35
Almost there.. I hope :-) 

Now the browser opens up, but the line `re.check( driver, "index" );` throws:

```
Tue Jul 09 18:29:30 CEST 2019:ERROR:java.lang.UnsupportedOperationException: No recheck adapter registered that can handle an object of class de.retest.web.selenium.UnbreakableDriver.
   java.lang.UnsupportedOperationException: No recheck adapter registered that can handle an object of class de.retest.web.selenium.UnbreakableDriver.
   	at de.retest.recheck.execution.RecheckAdapters.createHelpfulExceptionForMissingAdapter(RecheckAdapters.java:28)
   	at de.retest.recheck.execution.RecheckAdapters.lambda$findAdapterFor$1(RecheckAdapters.java:18)
   	at java.util.Optional.orElseThrow(Unknown Source)
   	at de.retest.recheck.execution.RecheckAdapters.findAdapterFor(RecheckAdapters.java:18)
   	at de.retest.recheck.RecheckImpl.check(RecheckImpl.java:117)
   	at de.retest.web.RecheckWebImpl.check(RecheckWebImpl.java:32)
   	at de.retest.recheck.Recheck$check$0.call(Unknown Source)
   	at de.retest.web.it.Script87.run(Script87.groovy:119)
   	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:90)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
   	at com.eviware.soapui.impl.wsdl.panels.teststeps.GroovyScriptStepDesktopPanel$RunAction$1.run(GroovyScriptStepDesktopPanel.java:250)
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   	at java.lang.Thread.run(Unknown Source)

```

**Comment by beatngu13** [comment] 2019-07-09 16:39
We are getting there! 😉 Could you add the current test class? My assumption: You are using `RecheckImpl` along with `UnbreakableDriver`? The latter requires `RecheckWebImpl` instead. Hope this helps: https://retest.github.io/docs/recheck-web/ways-of-using-recheck-web/

**Comment by lhimo** [comment] 2019-07-10 07:26
I tried both RecheckImpl with a normal ChromeDriver, as well as RecheckWebImpl with the UnbreakableDriver.. in the first case I get:

```
Wed Jul 10 09:22:48 CEST 2019:ERROR:java.util.ServiceConfigurationError: de.retest.recheck.RecheckAdapter: Provider de.retest.web.RecheckSeleniumAdapter could not be instantiated
   java.util.ServiceConfigurationError: de.retest.recheck.RecheckAdapter: Provider de.retest.web.RecheckSeleniumAdapter could not be instantiated
   	at java.util.ServiceLoader.fail(Unknown Source)
   	at java.util.ServiceLoader.access$100(Unknown Source)
   	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
   	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
   	at java.util.ServiceLoader$1.next(Unknown Source)
   	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
   	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
   	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
   	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
   	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
   	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
   	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
   	at java.util.stream.ReferencePipeline.findAny(Unknown Source)
   	at de.retest.recheck.execution.RecheckAdapters.findAdapterFor(RecheckAdapters.java:17)
   	at de.retest.recheck.RecheckImpl.check(RecheckImpl.java:117)
   	at de.retest.recheck.Recheck$check$0.call(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
   	at de.retest.web.it.Script1.run(Script1.groovy:119)
   	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:90)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
   	at com.eviware.soapui.impl.wsdl.panels.teststeps.GroovyScriptStepDesktopPanel$RunAction$1.run(GroovyScriptStepDesktopPanel.java:250)
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   	at java.lang.Thread.run(Unknown Source)
   Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/yaml/YAMLFactory
   	at de.retest.web.RecheckSeleniumAdapter.<init>(RecheckSeleniumAdapter.java:58)
   	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
   	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
   	at java.lang.reflect.Constructor.newInstance(Unknown Source)
   	at java.lang.Class.newInstance(Unknown Source)
   	... 24 more
   Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.dataformat.yaml.YAMLFactory
   	at java.net.URLClassLoader.findClass(Unknown Source)
   	at java.lang.ClassLoader.loadClass(Unknown Source)
   	at java.lang.ClassLoader.loadClass(Unknown Source)
   	... 30 more
```

in the latter I get the stacktrace of the previous comment. Maybe I'm missing some jars?

First case: `driver = new ChromeDriver( opts ); re = new RecheckImpl( options );`
Second case: `driver = new UnbreakableDriver( new ChromeDriver( opts ) ); re = new RecheckWebImpl( options );`

**Comment by beatngu13** [comment] 2019-07-10 08:11
When you say you are possibly missing some JARs, how do you manage dependencies in SoapUI? We currently offer no fat JAR that includes all transitive dependencies. So practically you need something which can pull Maven dependencies for you—at least until we release that fat JAR.

**Comment by lhimo** [comment] 2019-07-10 10:40
That's a very good question.. I tried with Grapes with no luck. 

I eventually downloaded the jars from jar-download.com and put them into the SoapUI lib folder. It seems to be working now, will try using it. Thanks!

**Comment by beatngu13** [comment] 2019-07-10 10:58
OK, I'm gonna close this issue but will let you know when we have a fat JAR for recheck-web. ✌️

**Closed as completed by beatngu13** 2019-07-10 10:58 UTC

**Comment by lhimo** [comment] 2019-07-10 12:07
Now I'm getting:

```
Wed Jul 10 14:04:49 CEST 2019:ERROR:java.lang.NoSuchMethodError: de.retest.recheck.TestCaseFinder.findTestCaseMethodInStack()Ljava/lang/StackTraceElement;
   java.lang.NoSuchMethodError: de.retest.recheck.TestCaseFinder.findTestCaseMethodInStack()Ljava/lang/StackTraceElement;
   	at de.retest.web.selenium.TestHealer.writeWarnLogForChangedIdentifier(TestHealer.java:211)
   	at de.retest.web.selenium.TestHealer.findElementById(TestHealer.java:84)
   	at de.retest.web.selenium.TestHealer.findElement(TestHealer.java:54)
   	at de.retest.web.selenium.TestHealer.findElement(TestHealer.java:49)
   	at de.retest.web.selenium.UnbreakableDriver.findElement(UnbreakableDriver.java:88)
   	at org.openqa.selenium.WebDriver$findElement$1.call(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
   	at de.retest.web.it.Script16.run(Script16.groovy:127)
   	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:90)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
   	at com.eviware.soapui.impl.wsdl.panels.teststeps.GroovyScriptStepDesktopPanel$RunAction$1.run(GroovyScriptStepDesktopPanel.java:250)
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   	at java.lang.Thread.run(Unknown Source)

```

Can this be related to a missing jar?

**Comment by beatngu13** [comment] 2019-07-10 13:39
See https://github.com/retest/recheck-web/issues/272#issuecomment-510064859.

**Comment by beatngu13** [comment] 2019-07-25 20:17
@lhimo as promised: as of recheck-web [v1.3.0](https://github.com/retest/recheck-web/releases/tag/v1.3.0), we are providing a JAR with all dependencies named `recheck-web-${VERSION}-jar-with-dependencies.jar`.

**Comment by lhimo** [comment] 2019-08-01 10:27
Wow! Thanks a lot
