### ISSUE TITLE
IllegalArgumentException: Unnamed path parameter

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck#697] opened 2020-03-24 14:28 UTC
## Describe the Bug

IllegalArgumentException: Unnamed path parameter cannot be null (path parameter at index 0 is null) error thrown during test execution.

Here's the relevant stack trace:
```
java.lang.IllegalArgumentException: Unnamed path parameter cannot be null (path parameter at index 0 is null)

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)

	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)

	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)

	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)

	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)

	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1612)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)

	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)

	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1262)

	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1029)

	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:816)

	at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)

	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)

	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)

	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1661)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)

	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)

	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1262)

	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1029)

	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:816)

	at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)

	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)

	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)

	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)

	at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:175)

	at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy)
```

### How to Reproduce?

This seemed to be a random failure. The weirdest part is that this was in an API only test so no browsers are involved.

### Setup

- recheck: 4.3.0
- Selenium version: 3.141.59
- Testing framework: TestNG 7.0.0
- OS: Ubuntu
- Java version: Java 8

**Comment by diba1013** [comment] 2020-03-24 14:45
Thanks for reporting this issue.

However, since there is no indication of a recheck stacktrace, there is only so much we can do. Could you point to any specifics, on why you consider that this is related to recheck alone?

Secondly, recheck version 4.3.0 seems odd. Where did you get that? I assume that this is only a typo as the latest version we have released is 1.10.2 (https://mvnrepository.com/artifact/de.retest/recheck). Please always use the latest versions, provided by official sources. If that is the actual version, we must strongly advice not to use it, as we have not released such a version and it might contain harmful code.

**Comment by javydreamercsw** [comment] 2020-03-24 16:41
1. See the last two lines in the trace: `at io.restassured.internal.RequestSpecificationImpl.post`
1. That's the version of rest assured. See below.

 ```
<dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>4.3.0</version>
  </dependency>
```

**Comment by diba1013** [comment] 2020-03-24 16:59
Ok, that explains things. You have the dependencies mixed up. This repository provides the dependency `de.retest:recheck:1.10.2` and has nothing to do with REST or similar. 

If you are sure that this is caused by the dependency described, you might want to give the guys at https://github.com/rest-assured/rest-assured (http://rest-assured.io/) a heads up.

Closing this as unrelated.

**Closed as completed by diba1013** 2020-03-24 16:59 UTC
